name: HTML checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: A job to test the html
    steps:
    - uses: chabad360/htmlproofer@master
      with:
          directory: "/src"
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer

