name: HTML link checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: A job to test check-html-links-action
    steps:
    - uses: actions/checkout@v2
    - name: check-html-links-action step
      id: check-links
      uses: modernweb-dev/check-html-links-action@v1
      with:
        doc-folder: 'src'
